version: "3.7"
services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    working_dir: /var/www
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
  mysql:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
